---

- name: Ensure config directory exists
  file:
    path: "{{ kubeconfig_root_dir }}"
    state: directory
  with_items:
    - "{{ groups['k8s_cluster'] }}"

- name: Store KubeConfig
  copy:
    content: "{{ hostvars[groups['k8s_cluster'][0]].kubeconfig.json.config }}"
    dest: "{{ kubeconfig_root_dir }}/config"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ groups['k8s_cluster'] }}"

