---

- name: Create Storage Class manifests
  template:
    src: templates/storageClassProvisioner.yml.j2
    dest: /tmp/storageClassProvisioner.yml
    owner: root
    group: root
    mode: 0644

- name: Storage class creation
  shell: "/usr/local/bin/kubectl apply -f /tmp/storageClassProvisioner.yml"
