---
- name: Stop and disable nm-cloud-setup.service.
  service:
    name: nm-cloud-setup.service
    state: stopped
    enabled: False
  register: need_reboot
  ignore_errors: yes

- name: Stop and disable nm-cloud-setup.timer.
  service:
    name: nm-cloud-setup.timer
    state: stopped
    enabled: False
  register: need_reboot
  ignore_errors: yes
