---
- import_tasks: common.yml

- import_tasks: chrony.yml

- import_tasks: folders.yml

- import_tasks: helm.yml
  tags: helm

- import_tasks: kubectl.yml

- import_tasks: docker.yml

- import_tasks: yum_packages.yml

- import_tasks: disable_nm_cloud.yml

- import_tasks: disable_firewall.yml

- import_tasks: disable_selinux.yml