# Inventory example
---
k8s_cluster:
  children:
    masters:
      hosts:
        hostname-mst01:
          ansible_host: 10.72.10.151
          rke2_type: server
        hostname-mst02:
          ansible_host: 10.72.10.152
          rke2_type: server
        hostname-mst03:
          ansible_host: 10.72.10.153
          rke2_type: server

    workers:
      hosts:
        hostname-wrk01:
          ansible_host: 10.72.10.154
          rke2_type: agent
        hostname-wrk02:
          ansible_host: 10.72.10.155
          rke2_type: agent
        hostname-wrk03:
          ansible_host: 10.72.10.156
          rke2_type: agent
        hostname-wrk04:
          ansible_host: 10.72.10.157
          rke2_type: agent
